"""Breeze client port for dependency injection and testing."""

from typing import Any, Protocol


class BreezeClientPort(Protocol):
    """Subset of BreezeConnect used by OptionDesk Pro."""

    def generate_session(self, api_secret: str, session_token: str) -> Any: ...

    def get_customer_details(self, api_session: str = "") -> dict[str, Any]: ...

    def get_funds(self) -> dict[str, Any]: ...

    def get_demat_holdings(self) -> dict[str, Any]: ...

    def get_portfolio_positions(self) -> dict[str, Any]: ...

    def get_portfolio_holdings(
        self,
        exchange_code: str = "",
        from_date: str = "",
        to_date: str = "",
        stock_code: str = "",
        portfolio_type: str = "",
    ) -> dict[str, Any]: ...

    def get_order_list(
        self,
        exchange_code: str = "",
        from_date: str = "",
        to_date: str = "",
    ) -> dict[str, Any]: ...

    def place_order(self, **kwargs: Any) -> dict[str, Any]: ...

    def modify_order(self, **kwargs: Any) -> dict[str, Any]: ...

    def cancel_order(
        self, exchange_code: str = "", order_id: str = ""
    ) -> dict[str, Any]: ...

    def get_quotes(self, **kwargs: Any) -> dict[str, Any]: ...

    def get_option_chain_quotes(self, **kwargs: Any) -> dict[str, Any]: ...

    def get_historical_data_v2(self, **kwargs: Any) -> dict[str, Any]: ...

    def get_stock_script_list(self) -> list[dict[str, str]]: ...

    def subscribe_feeds(self, **kwargs: Any) -> dict[str, Any]: ...

    def unsubscribe_feeds(self, **kwargs: Any) -> dict[str, Any]: ...

    def margin_calculator(
        self, lists: list[dict[str, str]], exchange_code: str
    ) -> dict[str, Any]: ...

    def ws_connect(self) -> None: ...

    def ws_disconnect(self) -> None: ...
